# Generated by Django 4.1.4 on 2023-08-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='names',
            new_name='name',
        ),
    ]
