# Generated by Django 4.1.4 on 2023-09-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_productimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='not required', verbose_name='description'),
        ),
    ]
