# Generated by Django 4.1.4 on 2023-09-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_offer_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/category/default.png', help_text='upload the category image', upload_to='images/category', verbose_name='category image'),
        ),
    ]
