# Generated by Django 4.1.4 on 2023-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_location_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.CharField(blank=True, help_text='required', max_length=255, verbose_name='contact'),
        ),
    ]
